# Role To Upgrade Tomcat

# Non Prod

# ansible-playbook -i inventory/nonprod run-upgrade-tomcat.yml --check
#ansible-playbook -i inventory/nonprod run-upgrade-tomcat.yml --limit {HOST LIST}

#ansible-playbook -i inventory/nonprod -u svc_confl run-upgrade-tomcat.yml --limit dev

# ansible-playbook -i inventory/nonprod run-upgrade-tomcat.yml --limit dev,uat

# Prod 

# ansible-playbook -i inventory/prod run-upgrade-tomcat.yml --limit prod

# ansible-playbook -i inventory/prod run-u/Users/sehteshamuddin/Downloads/confluence-infra-provision/run-upgrade-tomcat.ymlpgrade-tomcat.yml --limit prod,maa


---
- hosts: dev
  gather_facts: false
  serial: 1
  roles:
     - session_timouts

- hosts: prod
  gather_facts: false
  serial: 1
  roles:
     - session_timouts
